// ============================================================
//  INVOICE GENERATOR TRACKER — Google Apps Script
//
//  SETUP STEPS:
//  1. Create a new Google Sheet (or use an existing one)
//  2. Copy the Sheet ID from the URL:
//     https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID_HERE/edit
//  3. Paste the Sheet ID in the SPREADSHEET_ID variable below
//  4. Go to Extensions → Apps Script in the sheet
//  5. Paste this entire file, replacing any existing code
//  6. Click Deploy → New Deployment
//     - Type: Web App
//     - Execute as: Me
//     - Who has access: Anyone
//  7. Copy the Web App URL and paste it in app.js SHEET_URL
// ============================================================

// 👇 REPLACE THIS WITH YOUR SPREADSHEET ID
const SPREADSHEET_ID = 'YOUR_SPREADSHEET_ID_HERE';

// Handles POST (fetch/sendBeacon) requests
function doPost(e) {
  try {
    const raw = e.postData ? e.postData.contents : '{}';
    const data = JSON.parse(raw);
    handleData(data);
    return ContentService
      .createTextOutput(JSON.stringify({ status: 'ok' }))
      .setMimeType(ContentService.MimeType.JSON);
  } catch (err) {
    return ContentService
      .createTextOutput(JSON.stringify({ status: 'error', message: err.message }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

// Handles GET (image-ping fallback from Brave/Firefox)
function doGet(e) {
  try {
    if (e.parameter && e.parameter.data) {
      const slim = JSON.parse(decodeURIComponent(e.parameter.data));
      // Reconstruct a minimal payload from the slim GET data
      const data = {
        type: slim.t || 'session',
        event: slim.e || 'ping',
        user: slim.u || 'Anonymous',
        role: '',
        device: 'Unknown (beacon fallback)',
        browser: 'Unknown',
        timestamp: slim.ts || new Date().toISOString(),
      };
      handleData(data);
    }
    // Return a 1x1 transparent GIF so the image load succeeds
    return ContentService
      .createTextOutput('ok')
      .setMimeType(ContentService.MimeType.TEXT);
  } catch (err) {
    return ContentService.createTextOutput('error').setMimeType(ContentService.MimeType.TEXT);
  }
}

function handleData(data) {
  const ss = SpreadsheetApp.openById(SPREADSHEET_ID);
  if (data.type === 'session') {
    logSession(ss, data);
  } else if (data.type === 'document') {
    logDocument(ss, data);
  }
}

// ── SESSION LOG ─────────────────────────────────────────────
function logSession(ss, data) {
  let sheet = ss.getSheetByName('Sessions');
  if (!sheet) {
    sheet = ss.insertSheet('Sessions');
    sheet.appendRow([
      'Timestamp', 'Event', 'User Name', 'Role', 'Device', 'Browser'
    ]);
    sheet.getRange(1, 1, 1, 6).setFontWeight('bold').setBackground('#0d7b6e').setFontColor('#ffffff');
    sheet.setFrozenRows(1);
  }

  sheet.appendRow([
    new Date(data.timestamp),
    data.event || '',
    data.user || 'Anonymous',
    data.role || '',
    data.device || '',
    data.browser || '',
  ]);
}

// ── DOCUMENT LOG ────────────────────────────────────────────
function logDocument(ss, data) {
  let sheet = ss.getSheetByName('Documents');
  if (!sheet) {
    sheet = ss.insertSheet('Documents');
    sheet.appendRow([
      'Timestamp', 'Generated By', 'Role', 'Doc Type', 'Doc Number',
      'Business', 'Client', 'Items', 'Total', 'Currency'
    ]);
    sheet.getRange(1, 1, 1, 10).setFontWeight('bold').setBackground('#1a9b8a').setFontColor('#ffffff');
    sheet.setFrozenRows(1);
  }

  sheet.appendRow([
    new Date(data.timestamp),
    data.user || 'Anonymous',
    data.role || '',
    data.docType || '',
    data.docNumber || '',
    data.business || '',
    data.client || '',
    data.itemCount || 0,
    parseFloat(data.total) || 0,
    data.currency || 'KSh',
  ]);
}

// ── OPTIONAL: test this function manually in Apps Script ────
function testLog() {
  const ss = SpreadsheetApp.openById(SPREADSHEET_ID);
  logSession(ss, {
    type: 'session', event: 'test', user: 'Test User', role: 'Admin',
    device: 'Desktop', browser: 'Chrome', timestamp: new Date().toISOString()
  });
  logDocument(ss, {
    type: 'document', event: 'generated', user: 'Test User', role: 'Admin',
    docType: 'Invoice', docNumber: 'INV-001', business: 'Test Biz',
    client: 'Test Client', itemCount: 3, total: '6600', currency: 'KSh',
    timestamp: new Date().toISOString()
  });
  SpreadsheetApp.getUi().alert('✅ Test rows added to Sessions and Documents sheets!');
}
